#pragma config(Sensor, S1,     etaluotain,     sensorEV3_IRSensor)
#pragma config(Sensor, S2,     variluotain,    sensorEV3_Color)
#pragma config(Motor,  motorB,          MotorB,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          MotorC,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void liiku(int b, int c, int t) {
	motor[motorB] = b;
	motor[motorC] = c;
	wait1Msec(t);
	return;
}

/*
Kulkee eteenpain
params
   i: moottorin nopeus
time: kuinkakauan liikutaan eteen millisekunneissa
*/
void eteen(int i, int time) {
	liiku(i,i,time);
	return;
}

// Kiihdtytetaan eteen sekunnin sisalla
void kiihdyta(int k1, int k2) {
	int i = 0;
  while (i > -100) {
  	//eteen(i, 100);
  	liiku(i*k1,i*k2,100);
		i -= 10;
	}
	return;
}

// Kiihdtytetaan eteen sekunnin sisalla
void hidasta(int k1, int k2) {
	int i = -100;
  while (i <= 0) {
  	//eteen(i, 100);
  	liiku(i*k1,i*k2,50);
		i += 10;
	}
	return;
}

void hidastaEteen() {
	hidasta(1,1);	
}

void kiihdytaEteen() {
	kiihdyta(1,1);	
}

// Kaantyy noin vasemmalle
void vasemmalle() {
	kiihdyta(1,-1);
	hidasta(1,-1);
	return;
}

// Kaantyy noin oikealle
void oikealle() {
	kiihdyta(-1,1);
	hidasta(-1,1);
}

task main()
{

	kiihdytaEteen();
	while (true) {

		if (getIRDistance(etaluotain) < 40) {
			playTone(700, 100);
			hidastaEteen();
			vasemmalle();
			kiihdytaEteen();
		}
		
		eteen(-100, 100);
	}
}
