#pragma config(Sensor, S1,     etaluotain,     sensorEV3_IRSensor)
#pragma config(Sensor, S2,     variluotain,    sensorEV3_Color)
#pragma config(Sensor, S3,     Touchme,        sensorEV3_Touch)
#pragma config(Sensor, S4,     Gyroskooppi,           sensorEV3_Gyro, modeEV3Gyro_Rate)
#pragma config(Motor,  motorA,          MotorA,        tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          MotorB,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          MotorC,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Nykyinen vari
// short currentColour;

int subtask;
int maintask;
int nopeus;

// Abstrakti funktio, jonka kautta kaikki moottorikomennot ajetaan
void liiku(int b, int c) {
	motor[motorB] = b * -1;
	motor[motorC] = c * -1;
	wait1Msec(80);
	return;
}

void eteen(int i) {
	liiku(i,i);
	return;
}

// TODO nykiminen pois
void eteenGyrolla(short kulma) {
	if (SensorValue(Gyroskooppi)+10 > kulma) {
		liiku(nopeus,nopeus/2);
	} else if (SensorValue(Gyroskooppi)+10 < kulma) {
		liiku(nopeus/2,nopeus);
	} else {
		eteen(nopeus);
	}
}

void kaannyGyrolla(short kulma) {
	if (SensorValue(Gyroskooppi) > kulma) {
		liiku(nopeus,nopeus*-1);
	} else if (SensorValue(Gyroskooppi) < kulma) {
		liiku(nopeus*-1,nopeus);
	}
}

void kaanny(short kulma) {
	liiku(nopeus,nopeus*-1);
	/*
	if (SensorValue(Gyroskooppi) > kulma) {
		liiku(nopeus,nopeus*-1);
	} else if (SensorValue(Gyroskooppi) < kulma) {
		liiku(nopeus*-1,nopeus);
	}
	*/
}

void toteutaAliTehtavaa(int liikenopeus, int suunta, int anturi, short kulma) {
	
	displayCenteredBigTextLine(8, "liikenopeus: %d", liikenopeus);
	displayCenteredBigTextLine(10, "suunta: %d", suunta);
	displayCenteredBigTextLine(12, "anturi: %d", anturi);
	displayCenteredBigTextLine(14, "kulma: %d", kulma);

	switch(anturi) {
		case 0 :
			// ei mitaan
			break;
		case 1 :
			// gyro
			if (SensorValue(Gyroskooppi) == kulma) {
				subtask += 1;
				return;
			}
			break;
		case 2 :
			// infra
			if (getIRDistance(etaluotain) < 20) {
				subtask += 1;
				return;
			}
			break;
	}
	
	switch(liikenopeus) {
		case 0 :
			// täysillä
			nopeus = 100;
			break;
		case 1 :
			// hidasta
			if (nopeus == 0) {
				subtask += 1;
				return;
			}
			nopeus -= 10;
			break;
		case 2 :
			// kiihdyta
			if (nopeus == 100) {
				subtask += 1;
				return;
			}
			nopeus += 10;
			break;
	}
	
	switch(suunta) {
		case 0 :
			// eteen
			eteenGyrolla(kulma);
			break;
		case 1 :
			// kaanna
			kaanny(kulma);
			break;
	}
}

void toteutaTehtavaa(short kulma) {
	
	/*
	toteutaAliTehtavaa(hidasta/kiihdyta/täysillä, eteen/käännä, kulma);
	täysillä = 0
	hidasta = 1
	kiihdyta = 2
	
	
	eteen = 0
	käännä = 1
	
	ei mitaan = 0
	gyro = 1
	infra = 2
	*/
	
	switch(subtask) {
		case 0 :
			// hidastaeteen
			toteutaAliTehtavaa(1, 0, 0, kulma);
			break;
		case 1 :
			// kaannakiihdyta
			toteutaAliTehtavaa(2, 1, 0, kulma);
			break;
			/*
		case 2 :
			// täysilläkaanna
			toteutaAliTehtavaa(0, 1, 1, kulma);
			break;
			*/
		case 2 :
			// hidastakäännä
			toteutaAliTehtavaa(1, 1, 0, kulma);
			break;
		case 3 :
			// kiihdytaeteen
			toteutaAliTehtavaa(2, 0, 2, kulma);
			break;
		case 4 :
			// täysilläeteen
			toteutaAliTehtavaa(0, 0, 2, kulma);
			break;
		case 5 :
			// vaihda maintask
			subtask = 0;
			maintask += 1;
			break;
	}
}

task main() {
	
	setSensorMode(Gyroskooppi, modeEV3Gyro_Angle);
	resetGyro(Gyroskooppi);
	
	maintask = 0;
	subtask = 4;
	nopeus = 0;

	while (true) {
		
		displayCenteredBigTextLine(1, "main: %d", maintask);
		displayCenteredBigTextLine(3, "sub: %d", subtask);
		displayCenteredBigTextLine(6, "Cangle: %d", SensorValue(Gyroskooppi));
		
		switch(maintask) {
			case 0 :
				// kohti
				toteutaTehtavaa(0);
				break;
			case 1 :
				// vasen
				toteutaTehtavaa(-90);
				break;
			case 2 :
				// kohti
				toteutaTehtavaa(0);
				break;
			case 3 :
				// oikea
				toteutaTehtavaa(90);
				break;
		}
		
		if (maintask > 3) {
			maintask = 0;	
		}
	}
}
