#pragma config(Sensor, S1,     etaluotain,     sensorEV3_IRSensor)
#pragma config(Sensor, S2,     variluotain,    sensorEV3_Color)
#pragma config(Sensor, S3,     Touchme,        sensorEV3_Touch)
#pragma config(Motor,  motorB,          MotorB,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          MotorC,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Tyolista maaraa jarjestyksen, jossa tehtävät toteutetaan, kun
infrasensori huomaa edessaan jotain.
*/
int tyolista[3] = {2, 1, 0};
// Missä kohtaa tyolistaa ollaan menossa
int vaihe = 0;
// Lopetuksen muuttuja
bool roskilla = false;

// Abstrakti funktio, jonka kautta kaikki moottorikomennot ajetaan
void liiku(int b, int c, int t) {
	motor[motorB] = b;
	motor[motorC] = c;
	wait1Msec(t);
	return;
}

/*
Kulkee eteenpain
params
   i: moottorin nopeus
time: kuinkakauan liikutaan eteen millisekunneissa
*/
void eteen(int i, int time) {
	liiku(i,i,time);
	return;
}

// Kiihdtytetaan eteen sekunnin sisalla
void kiihdyta(int k1, int k2) {
	int i = 0;
  while (i > -100) {
  	//eteen(i, 100);
  	liiku(i*k1,i*k2,60);
		i -= 10;
	}
	return;
}

// Kiihdtytetaan eteen sekunnin sisalla
void hidasta(int k1, int k2) {
	int i = -100;
  while (i <= 0) {
  	//eteen(i, 100);
  	liiku(i*k1,i*k2,60);
		i += 10;
	}
	return;
}

// Hidastaa kaantymatta
void hidastaEteen() {
	hidasta(1,1);
}

// Kiihdyttaa kaantymatta
void kiihdytaEteen() {
	kiihdyta(1,1);
}

// Kaantyy noin vasemmalle
void vasemmalle() {
	kiihdyta(1,-1);
	hidasta(1,-1);
	return;
}

// Kaantyy noin oikealle
void oikealle() {
	kiihdyta(-1,1);
	hidasta(-1,1);
}

void toteutaTehtava() {
	switch(tyolista[vaihe]) {
		case 0 :
			// Lopetus, eli roskille saapuminen
			playTone(700, 100);
			displayCenteredBigTextLine(4, "Roskilla");
			roskilla = true;
			liiku(0,0,1000);
			break;
		case 1 :
			// Oikealle kaantyminen
			displayCenteredBigTextLine(4, "Oikealle");
			hidastaEteen();
			oikealle();
			break;
		case 2 :
			// Vasemmalle kaantyminen
			displayCenteredBigTextLine(4, "Vasemalle");
			hidastaEteen();
			vasemmalle();
			break;
		default :
			displayCenteredBigTextLine(4, "default");
			break;
	}
	vaihe += 1;
}

task main()
{

	while (true) {
		// Poistutaan while-lauseesta, jos roskilla
		if (roskilla) {
			break;
		}

		// Jos edessa jotain, tee tehtava
		if (getIRDistance(etaluotain) < 20) {
			toteutaTehtava();
		}

		// Jos kosketusanturi pohjassa, eli lasti kyydissa
		if (SensorValue[Touchme])
		{
			setLEDColor(ledGreen);
			displayCenteredBigTextLine(4, "Eteen");
			if (!roskilla) {
				eteen(-100, 100);
			}
		}
		// Jos ei lastia
		else
		{
			displayCenteredBigTextLine(4, "Odotetaan roskia");
			setLEDColor(ledGreen);
			motor[motorB] = 0;
			motor[motorC] = 0;
		}
	}
}
